name: dotnet package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet build katas/
      - name: Check format issues
        run: dotnet format --verify-no-changes katas/
      - name: Run tests
        run: dotnet test katas/ -l html --collect:"XPlat Code Coverage"